model_name: google/gemma-2-27b-it
exp_name: llm_surround

lr: 5.0e-5
head_lr: 5.0e-6
epochs: 1
weight_decay: 0.01

lora_r: 64
lora_alpha: 16
lora_dropout: 0.
target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj

training:
  batch_size: 4
  accum: 2
  max_length: 1800

validation:
  batch_size: 4
  accum: 1
  max_length: 8192