model_name: sfairXC/FsfairX-Gemma2-RM-v0.1
exp_name: llm_pseudo_rm_orpo_500k_no_lstm_no_cap_rd_2

lr: 1.0e-4
epochs: 1
weight_decay: 0.01

lora_r: 64
lora_alpha: 16
lora_dropout: 0.05
target_modules:
  - q_proj
  - k_proj
  - v_proj
  - o_proj
  - gate_proj
  - up_proj
  - down_proj

training:
  batch_size: 2
  accum: 1
  max_length: 1800

validation:
  batch_size: 4
  accum: 1
  max_length: 8192